config {
    assertions: {
        nonNull: ["customer_id", "order_id"],
        uniqueKey: ["customer_id", "order_id"],
        rowConditions: [acceptedValues.acceptedValues( "status", "'placed', 'shipped', 'completed', 'return_pending', 'returned'" )]
    },
    schema: "raw",
    type: 'view'
} 

select
    id as order_id,
    user_id as customer_id,
    order_date,
    status

from `dbt-tutorial`.jaffle_shop.orders